### ISSUE TITLE
Error EXEPTION

### ISSUE THREAD

**Issue by pioniziolek** [michaelrcarroll/script.kodi.hue.ambilight#11]
Hi, 
I hope you can easily sovle this issue.
I'm not able to start script.kodi.hue.ambilight on kodi 15.2 (windows 10) with following log exception in logfile:

00:03:48 T:9364   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "C:\Users\Gandalf\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\default.py", line 462, in <module>
                                                hue = Hue(settings, args)
                                              File "C:\Users\Gandalf\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\default.py", line 95, in __init__
                                                self.update_settings()
                                              File "C:\Users\Gandalf\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\default.py", line 197, in update_settings
                                                self.light[0] = Light(self.settings.light1_id, self.settings)
                                              File "C:\Users\Gandalf\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\resources\lib\tools.py", line 102, in __init__
                                                self.get_current_setting()
                                              File "C:\Users\Gandalf\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\resources\lib\tools.py", line 118, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--

I saw this issue on some forums already but with no solution to date.
Please advice how to

**Comment by pioniziolek** [comment]
Hi again, 
I'm not a programmer but try to unerstand the issue. 
I found on the net same problem solved by system reinstallation. It will not help in my case - same isssue occures on both PC I'm using. 
Is it possible that this problem is generated by different Python version installed on my PC?
My Win 10 is x64. Does x32/x64 make difference for Python compatibility?

Regards

**Comment by michaelrcarroll** [comment]
Hey @pioniziolek. Python comes bundled with Kodi, so you should be ok. Can you provide the file from ```C:\Users\Gandalf\AppData\Roaming\Kodi\userdata\addon_data\script.kodi.hue.ambilight\```? It seems like something is messed up in that file.

Unless you *must* retain these settings, you should be ok to delete the file and then see if the issue persists.

**Comment by pioniziolek** [comment]
Hi, 
here you are:
<settings>
<setting id="ambilight_dim" value="true" />
<settingid="ambilight_dim_group" value="0" />
<setting id="ambilight_info" value="" />
<setting id="ambilight_max" value="90" />
<setting id="ambilight_min" value="7" />
<setting id="bridge_ip" value="192.168.0.111" />
<setting id="bridge_user" value="1b816aad85f0afe2cd7d0550130e8894" />
<setting id="color_bias" value="18" />
<setting id="debug" value="true" />
<setting id="dim_time" value="0.500000" />
<setting id="dimmed_bri" value="22" />
<setting id="dimmed_hue" value="22755" />
<setting id="discover_bridge" value="" />
<setting id="group_id" value="0" />
<setting id="light" value="0" />
<setting id="light1_id" value="1" />
<setting id="light2_id" value="2" />
<setting id="light3_id" value="3" />
<setting id="misc_disableshort" value="false" />
<setting id="misc_initialflash" value="false" />
<setting id="mode" value="1" />
<setting id="override_hue" value="true" />
<setting id="override_undim_bri" value="false" />
<setting id="undim_bri" value="80" />
<setting id="undim_hue" value="22755" />
</settings>

The only issue I see are different regional settings - in my computer decimal mark was a coma instead of dot. I changed it but with no result.

**Comment by michaelrcarroll** [comment]
Hi @pioniziolek. I was unable to duplicate your issue with my local setup. Please try to delete ```settings.xml``` and try to start the addon again.

Please follow the instructions in the [Debugging](https://github.com/michaelrcarroll/script.kodi.hue.ambilight#debugging) section of the readme to record and submit log files of what happens.

**Comment by pioniziolek** [comment]
I solved this issue. 
Script crashed because of wrong "Light bulbs ID" 2 and 3 parameter. I modified it and everything works nice now.

**Comment by michaelrcarroll** [comment]
Great! I think I ended up coming across the same issue, and https://github.com/michaelrcarroll/script.kodi.hue.ambilight/commit/6ed2d12cc5b8fa5033d15162e8082173e6d2f361 will help out with this a lot (shows a better error message to let you know what went wrong).
