### ISSUE TITLE
Descriptions For Settings

### ISSUE THREAD

**Issue by leejk421** [michaelrcarroll/script.kodi.hue.ambilight#25]
It would be very helpful if descriptions could be added to each setting of this addon. I've seen this type of information present in the main Kodi settings, where the description is shown at the bottom of the window, but not sure if this is possible with addons. It would be a valuable aid for proper configuration.

**Comment by michaelrcarroll** [comment]
@leejk421 agreed. i should make a wiki page for this to have better human-readable descriptions for the settings. i'll try for this on 0.8 release.

**Comment by michaelrcarroll** [comment]
https://github.com/michaelrcarroll/script.kodi.hue.ambilight/wiki

Current with the 0.8b2 settings, will update to reflect changes as things progress. thanks for the suggestion.
