### ISSUE TITLE
Automatic Discovery not working with new Hub

### ISSUE THREAD

**Issue by EasyBouncer** [michaelrcarroll/script.kodi.hue.ambilight#28]
Hello Sir,

I had your add-on working without any problems on the first try when I first got my HUE hub 2.0. That one unfortunately had to be replaced so I installed my new one, and proceeded to run the auto discovery option. I was at first getting an error message so I proceeded to update the scripts and do a Kodi fresh install. I no longer receive the error but when I try auto discovery it just says it has begun its search but never does anything else. The following is from the log:

03:14:25 T:9388  NOTICE: Kodi Hue service started, version: 0.8
03:14:43 T:9116 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.

The closest I've been able to come is when I input the network IP of the hub manually and leave the ID blank. Kodi starts and a message appears saying bridge connected but it doesn't work or take control of any of the lights.

Hope we can sort this out.

Thanks

**Comment by EasyBouncer** [comment]
In addition, these are 2 other codes I've been receiving when using the bridge ID:

03:42:54 T:4716   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py", line 105, in onPlayBackStarted
                                                state_changed("started", self.duration)
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py", line 680, in state_changed
                                                for l in hue.light:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--


03:43:50 T:4716   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: ('Bridge Error', 1, {u'type': 1, u'description': u'unauthorized user', u'address': u'/lights'})
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py", line 70, in onSettingsChanged
                                                hue.update_settings()
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py", line 379, in update_settings
                                                self.light[0] = Light(self.settings.light1_id, self.settings)
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\resources\lib\tools.py", line 79, in __init__
                                                self.get_current_setting()
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\resources\lib\tools.py", line 105, in get_current_setting
                                                raise ValueError("Bridge Error", err["type"], err)
                                            ValueError: ('Bridge Error', 1, {u'type': 1, u'description': u'unauthorized user', u'address': u'/lights'})
                                            -->End of Python script error report<--


03:44:03 T:4716 WARNING: CPythonInvoker(1, C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py): the python script "C:\Users\User\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-0.8b1\default.py" has left several classes in memory that we couldn't clean up. The classes include: class PythonBindings::XBMCAddon_xbmc_Player_Director

**Comment by michaelrcarroll** [comment]
Hi @EasyBouncer. In your second post: the first error is due to #29 (the add-on did not properly load the settings on first launch). the second error is showing that kodi is trying to talk to the bridge, but is being rejected because of the username not being authorized.

Unfortunately, manually setting an IP address and then requesting a username is not currently possible.

Try to re-run the auto discovery, and if that still doesn't work, try the new "reset settings" in the upcoming 0.8b2 on the advanced settings tab (you'll need to disable and re-enable the script). Post back the results!

**Comment by EasyBouncer** [comment]
Thanks for your help! I'm not sure what was happening but all of a sudden the auto discovery was working and the hue bridge was found and connected properly. The only problem I was having after that was the hue bridge ID which changed every time I closed and reopened Kodi. This problem is gone now with the recent beta2 release. Thanks again.
