### ISSUE TITLE
Kodi DSPlayer MadVR doesn't work

### ISSUE THREAD

**Issue by Natrixz** [michaelrcarroll/script.kodi.hue.ambilight#7]
When using MadVR DSPlayer it does not work. Just turns off lights at start of playback and does not do anything after that

**Comment by michaelrcarroll** [comment]
Unlikely to be able to fix this. All Mac/linux household, no way to set up/debug MadVR DSPlayer. Probable cause: I listen for playback events from the Kodi player indicating that play/pause has occurred, I don't think MadVR/DSPlayer sends these events back.

**Comment by Natrixz** [comment]
I think it does send those, May have an idea as to why it doesn't work.
How do you determine what color to set? Do you make a print screen?

Kind regards,
Nick
Op 10 okt. 2015 23:47 schreef "Michael Carroll" <notifications@github.com>:

**Comment by michaelrcarroll** [comment]
Ah, I didn't know you were talking about the Ambilight features. I actually don't use those and haven't made any modifications from @cees-elzinga's original code. 

Long story short: https://github.com/michaelrcarroll/script.kodi.hue.ambilight/blob/master/default.py#L398
A new instance of the Kodi Player is created and then it grabs frames to determine the most used colors.
